#!/bin/bash

eval last=\"\${$#}\"
[ -e "$last" ] && last="$(wslpath -w "$last")"

ProgramFiles="$(wslpath "$(cmd.exe /c "<nul set /p=%ProgramFiles%" 2>/dev/null)")"

PATH="${PATH:+"${PATH}:"}${ProgramFiles}/Chromium/Application:${ProgramFiles} (x86)/Chromium/Application" chrome.exe ${@:1:$(($# - 1))} "$last" &
