#!/bin/sh

ProgramFiles="$(wslpath "$(cmd.exe /c "<nul set /p=%ProgramFiles%" 2>/dev/null)")"

PATH="${PATH:+"${PATH}:"}${ProgramFiles}/Google/Chrome/Application:${ProgramFiles} (x86)/Google/Chrome/Application" chrome.exe "$@" &
