#!/bin/bash

eval last=\"\${$#}\"
[ -e "$last" ] && last="$(wslpath -w "$last")"

ProgramFiles="$(wslpath "$(cmd.exe /c "<nul set /p=%ProgramFiles%" 2>/dev/null)")"

PATH="${PATH:+"${PATH}:"}${ProgramFiles}/Google/Chrome/Application:${ProgramFiles} (x86)/Google/Chrome/Application" chrome.exe ${@:1:$(($# - 1))} "$last" &
