#!/bin/sh

ProgramFiles="$(wslpath "$(cmd.exe /c "<nul set /p=%ProgramFiles%" 2>/dev/null)")"

PATH="${PATH:+"${PATH}:"}${ProgramFiles}/Chromium/Application:${ProgramFiles} (x86)/Chromium/Application" chrome.exe "$@" &
