#!/bin/sh

ProgramFiles="$(wslpath "$(cmd.exe /c "<nul set /p=%ProgramFiles%" 2>/dev/null)")"

PATH="${PATH:+"${PATH}:"}${ProgramFiles}/Mozilla Firefox:${ProgramFiles} (x86)/Mozilla Firefox" firefox.exe "$@" &

