#!/bin/bash

eval last=\"\${$#}\"
[ -e "$last" ] && last="$(wslpath -w "$last")"

ProgramFiles="$(wslpath "$(cmd.exe /c "<nul set /p=%ProgramFiles%" 2>/dev/null)")"

if command -v gimp.exe  >/dev/null 2>&1; then
  gimp.exe ${@:1:$(($# - 1))} "$last" &
elif [ -d "${ProgramFiles}/GIMP 2" ]; then
  cd "${ProgramFiles}/GIMP 2"
  gimp="$(ls "./bin/"gimp-2.*.exe)"
  $gimp ${@:1:$(($# - 1))} "$last" &
elif [ -d "${ProgramFiles} (x86)/GIMP 2" ]; then
  cd "${ProgramFiles} (x86)/GIMP 2"
  gimp="$(ls "./bin/"gimp-2.*.exe)"
  $gimp ${@:1:$(($# - 1))} "$last" &
else
  echo "No executable gimp.exe found!"
fi
