#!/bin/bash

[ $# -ge 1 ] && eval last=\"\${$#}\"
[ -e "$last" ] && last="$(winpath -aw "$last")" && set -- "${@:1:$(($#-1))}"

ProgramFiles="$(winpath "$(cmd.exe /c "<nul set /p=%ProgramFiles%" 2>/dev/null)")"

if command -v gimp.exe  >/dev/null 2>&1; then
  gimp.exe "$@" ${last:+"$last"}
elif [ -d "${ProgramFiles}/GIMP 2" ]; then
  cd "${ProgramFiles}/GIMP 2"
  gimp="$(ls "./bin/"gimp-2.*.exe)"
  $gimp "$@" ${last:+"$last"}
elif [ -d "${ProgramFiles} (x86)/GIMP 2" ]; then
  cd "${ProgramFiles} (x86)/GIMP 2"
  gimp="$(ls "./bin/"gimp-2.*.exe)"
  $gimp "$@" ${last:+"$last"}
else
  echo "No executable gimp.exe found!"
fi
