#!/bin/sh

if command -v goldendict.exe  >/dev/null 2>&1; then
  goldendict.exe "$@" &
elif command -v "${ProgramFiles}/GoldenDict"/goldendict.exe >/dev/null 2>&1; then
  "${ProgramFiles}/GoldenDict"/goldendict.exe "$@" &
elif command -v "${ProgramFiles} (x86)/GoldenDict"/goldendict.exe >/dev/null 2>&1; then
  "${ProgramFiles} (x86)/GoldenDict"/goldendict.exe "$@" &
else
  echo "No executable goldendict.exe  found!"
fi
