#!/bin/sh

ProgramFiles="$(wslpath "$(cmd.exe /c "<nul set /p=%ProgramFiles%" 2>/dev/null)")"

PATH="${PATH:+"${PATH}:"}${ProgramFiles}/GoldenDict:${ProgramFiles} (x86)/GoldenDict" goldendict.exe "$@" &

