#!/bin/bash

[ $# -ge 1 ] && eval last=\"\${$#}\" && shift
[ -e "$last" ] && last="$(winpath -aw "$last")"

ProgramFiles="$(winpath "$(cmd.exe /c "<nul set /p=%ProgramFiles%" 2>/dev/null)")"

if command -v gvim.bat  >/dev/null 2>&1; then
  if [ -n ${WSL_DISTRO_NAME+x} ]; then
    cmd.exe /c gvim.bat "$@" ${last:+"$last"} >/dev/null 2>&1
  elif [ -n ${MSYSTEM+x} ]; then
    gvim.bat "$@" ${last:+"$last"}
  fi
else
  PATH="${PATH:+"${PATH}:"}${ProgramFiles}/Vim/bin:${ProgramFiles} (x86)/Vim/bin" gvim.exe "$@" ${last:+"$last"}
fi
