#!/bin/sh

if command -v gvim.bat  >/dev/null 2>&1; then
  cmd.exe /c start /b gvim.bat "$@" &
elif command -v gvim.exe  >/dev/null 2>&1; then
  gvim.exe "$@" &
elif command -v "${ProgramFiles}/Vim/bin"/gvim.exe >/dev/null 2>&1; then
  "${ProgramFiles}/Vim/gvim.exe" "$@" &
elif command -v "${ProgramFiles} (x86)/Vim/bin"/gvim.exe >/dev/null 2>&1; then
  "${ProgramFiles} (x86)/Vim/gvim.exe" "$@" &
else
  echo "No executable gvim.exe  found!"
fi
