#!/bin/sh

if command -v inkscape.exe  >/dev/null 2>&1; then
  inkscape.exe "$@" &
elif command -v "${ProgramFiles}/Inkscape"/inkscape.exe >/dev/null 2>&1; then
  "${ProgramFiles}/Inkscape/inkscape.exe" "$@" &
elif command -v "${ProgramFiles} (x86)/Inkscape"/inkscape.exe >/dev/null 2>&1; then
  "${ProgramFiles} (x86)/Inkscape/inkscape.exe" "$@" &
else
  echo "No executable inkscape.exe  found!"
fi
