#!/bin/sh

ProgramFiles="$(wslpath "$(cmd.exe /c "<nul set /p=%ProgramFiles%" 2>/dev/null)")"

PATH="${PATH:+"${PATH}:"}${ProgramFiles}/Krita (x64)/bin:${ProgramFiles} (x86)/Krita (x86)/bin" krita.exe "$@" &
