#!/bin/bash

[ $# -ge 1 ] && eval last=\"\${$#}\"
[ -e "$last" ] && last="$(winpath -aw "$last")" && set -- "${@:1:$(($#-1))}"

ProgramFiles="$(winpath "$(cmd.exe /c "<nul set /p=%ProgramFiles%" 2>/dev/null)")"

PATH="${PATH:+"${PATH}:"}${ProgramFiles}/LibreOffice/program:${ProgramFiles} (x86)/LibreOffice/program" soffice.exe "$@" ${last:+"$last"}

