#!/bin/bash

[ $# -ge 1 ] && eval last=\"\${$#}\" && shift
[ -e "$last" ] && last="$(wslpath -w "$last")"

ProgramFiles="$(wslpath "$(cmd.exe /c "<nul set /p=%ProgramFiles%" 2>/dev/null)")"

if command -v magick.exe  >/dev/null 2>&1; then
  magick.exe "$@" ${last:+"$last"}
else
  magick="$(ls "${ProgramFiles}/ImageMagick"*/magick.exe)" >/dev/null 2>&1 || magick="$(ls "${ProgramFiles} (x86)/ImageMagick"*/magick.exe)" >/dev/null 2>&1
  if command -v "$magick" >/dev/null 2>&1; then
    "$magick" "$@" ${last:+"$last"}
  else
    echo "No executable magick.exe  found!"
  fi
fi
