#!/bin/bash

[ $# -ge 1 ] && eval last=\"\${$#}\"
[ -e "$last" ] && last="$(winpath -aw "$last")" && set -- "${@:1:$(($#-1))}"

if command -v mupdf.exe  >/dev/null 2>&1; then
  mupdf.exe "$@" ${last:+"$last"}
else
  echo "No executable mupdf.exe  found!"
fi
