#!/bin/bash

eval last=\"\${$#}\"
[ -e "$last" ] && last="$(wslpath -w "$last")"

if command -v mupdf.exe  >/dev/null 2>&1; then
  mupdf.exe ${@:1:$(($# - 1))} "$last" &
else
  echo "No executable mupdf.exe  found!"
fi
