#!/bin/sh

ProgramFiles="$(wslpath "$(cmd.exe /c "<nul set /p=%ProgramFiles%" 2>/dev/null)")"

PATH="${PATH:+"${PATH}:"}${ProgramFiles}/Okular/bin:${ProgramFiles} (x86)/Okular/bin" okular.exe "$@" &

