#!/bin/bash

[ $# -ge 1 ] && eval last=\"\${$#}\" && shift
[ -e "$last" ] && last="$(winpath -aw "$last")"

ProgramFiles="$(winpath "$(cmd.exe /c "<nul set /p=%ProgramFiles%" 2>/dev/null)")"

if command -v scribus.exe  >/dev/null 2>&1; then
  scribus.exe "$@" ${last:+"$last"}
else
  scribus="$(ls "${ProgramFiles}/Scribus"*/scribus.exe)" >/dev/null 2>&1 || scribus="$(ls "${ProgramFiles} (x86)/Scribus"*/scribus.exe)" >/dev/null 2>&1
  if command -v "$scribus" >/dev/null 2>&1; then
    "$scribus" "$@" ${last:+"$last"}
  else
    echo "No executable scribus.exe  found!"
  fi
fi
