#!/bin/sh

if command -v scribus.exe  >/dev/null 2>&1; then
  scribus.exe "$@" &
else
  scribus="$(ls "${ProgramFiles}/Scribus"*/scribus.exe)" >/dev/null 2>&1 || scribus="$(ls "${ProgramFiles} (x86)/Scribus"*/scribus.exe)" >/dev/null 2>&1
  if command -v "$scribus" >/dev/null 2>&1; then
    "$scribus" "$@"
  else
    echo "No executable scribus.exe  found!"
  fi
fi
