#!/bin/bash

[ $# -ge 1 ] && eval last=\"\${$#}\"
[ -e "$last" ] && last="$(winpath -aw "$last")" && set -- "${@:1:$(($#-1))}"

ProgramFiles="$(winpath "$(cmd.exe /c "<nul set /p=%ProgramFiles%" 2>/dev/null)")"

PATH="${PATH:+"${PATH}:"}${ProgramFiles}/SMplayer:${ProgramFiles} (x86)/SMplayer" smplayer.exe "$@" ${last:+"$last"}

