#!/bin/bash

eval last=\"\${$#}\"
[ -e "$last" ] && last="$(wslpath -w "$last")"

ProgramFiles="$(wslpath "$(cmd.exe /c "<nul set /p=%ProgramFiles%" 2>/dev/null)")"

PATH="${PATH:+"${PATH}:"}${ProgramFiles}/SMplayer:${ProgramFiles} (x86)/SMplayer" smplayer.exe ${@:1:$(($# - 1))} "$last" &

