#!/usr/bin/env bash

[ -n "${IS_WSL}" ] && [ -z "${WSL_DISTRO_NAME+x}" ] && export WSL_DISTRO_NAME="$IS_WSL"

if [ -n ${WSL_DISTRO_NAME+x} ]; then
  wslpath "$@"
elif [ -n ${MSYSTEM+x} ]; then
  cygpath "$@"
else 
  echo "$@"
fi
